[versions]
agp = "9.1.1"
kotlin = "2.2.10"
ksp = "2.2.10-2.0.2"
composeBom = "2026.04.01"
activityCompose = "1.12.1"
room = "2.8.5"
camerax = "1.6.2"
core = "1.17.0"
lifecycle = "2.10.0"
appcompat = "1.7.1"
work = "2.12.0"
exif = "1.4.1"
biometric = "1.1.0"

[libraries]
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
compose-foundation = { module = "androidx.compose.foundation:foundation" }
compose-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
compose-tooling = { module = "androidx.compose.ui:ui-tooling" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "core" }
lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
room-testing = { module = "androidx.room:room-testing", version.ref = "room" }
camera-core = { module = "androidx.camera:camera-core", version.ref = "camerax" }
camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camerax" }
camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camerax" }
camera-view = { module = "androidx.camera:camera-view", version.ref = "camerax" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
work = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }
biometric = { module = "androidx.biometric:biometric", version.ref = "biometric" }
exif = { module = "androidx.exifinterface:exifinterface", version.ref = "exif" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
